from(bucket: "advanced_db")
  |> range(start: _start, stop: _end)
  |> filter(fn: (r) => r["_measurement"] == "order_book")
  |> filter(fn: (r) => r["_field"] == "ask_price_1" or r["_field"] == "bid_price_1")
  |> filter(fn: (r) => r["symbol"] == "BTC-USDT")
  |> group(columns: ["_time", "_measurement"], mode:"by")
  |> mean()
  |> keep(columns: ["_time", "_value"])
  |> group()
